# Spring Boot configuration
spring:
  profiles:
    active: test
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
  # JPA properties
  jpa:
    hibernate:
      dll-auto: create-drop #none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console
# Logger configuration
logging:
  level:
    web: debug
# Server configuration
server:
  port: 80 #set your port